spring.application.name=backend
#comando para inicie la depuracion si tener una base de datos , este es el comando para funcione sin tener uno
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8081
