spring.application.name=mypelink-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mypelink_db
spring.datasource.username=mypelink_user
spring.datasource.password=Systemout20
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=5432

logging.level.org.springframework.security=DEBUG
logging.level.com.mypelink=DEBUG