spring.application.name=mypelink-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mypelink_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# AWS S3 CONFIGURATION (ARCHIVOS Y PDFs)
# ==========================================
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_BUCKET_NAME}

# --- MYPElink Admins ---
admin.enzo.name=${ADMIN_ENZO_NAME}
admin.enzo.email=${ADMIN_ENZO_EMAIL}
admin.enzo.password=${ADMIN_ENZO_PWD}
admin.enzo.dni=${ADMIN_ENZO_DNI}
admin.enzo.telefono=${ADMIN_ENZO_TELEFONO}
admin.enzo.codigo=${ADMIN_ENZO_CODIGO}
admin.enzo.carrera=${ADMIN_ENZO_CARRERA}
admin.enzo.universidad=${ADMIN_ENZO_UNIVERSIDAD}

admin.marco.name=${ADMIN_MARCO_NAME}
admin.marco.email=${ADMIN_MARCO_EMAIL}
admin.marco.password=${ADMIN_MARCO_PWD}
admin.marco.dni=${ADMIN_MARCO_DNI}
admin.marco.telefono=${ADMIN_MARCO_TELEFONO}
admin.marco.codigo=${ADMIN_MARCO_CODIGO}
admin.marco.carrera=${ADMIN_MARCO_CARRERA}
admin.marco.universidad=${ADMIN_MARCO_UNIVERSIDAD}

admin.jhon.name=${ADMIN_JHON_NAME}
admin.jhon.email=${ADMIN_JHON_EMAIL}
admin.jhon.password=${ADMIN_JHON_PWD}
admin.jhon.dni=${ADMIN_JHON_DNI}
admin.jhon.telefono=${ADMIN_JHON_TELEFONO}
admin.jhon.codigo=${ADMIN_JHON_CODIGO}
admin.jhon.carrera=${ADMIN_JHON_CARRERA}
admin.jhon.universidad=${ADMIN_JHON_UNIVERSIDAD}

admin.gianpiero.name=${ADMIN_GIANPIERO_NAME}
admin.gianpiero.email=${ADMIN_GIANPIERO_EMAIL}
admin.gianpiero.password=${ADMIN_GIANPIERO_PWD}
admin.gianpiero.dni=${ADMIN_GIANPIERO_DNI}
admin.gianpiero.telefono=${ADMIN_GIANPIERO_TELEFONO}
admin.gianpiero.codigo=${ADMIN_GIANPIERO_CODIGO}
admin.gianpiero.carrera=${ADMIN_GIANPIERO_CARRERA}
admin.gianpiero.universidad=${ADMIN_GIANPIERO_UNIVERSIDAD}

admin.segundo.name=${ADMIN_SEGUNDO_NAME}
admin.segundo.email=${ADMIN_SEGUNDO_EMAIL}
admin.segundo.password=${ADMIN_SEGUNDO_PWD}
admin.segundo.dni=${ADMIN_SEGUNDO_DNI}
admin.segundo.telefono=${ADMIN_SEGUNDO_TELEFONO}
admin.segundo.codigo=${ADMIN_SEGUNDO_CODIGO}
admin.segundo.carrera=${ADMIN_SEGUNDO_CARRERA}
admin.segundo.universidad=${ADMIN_SEGUNDO_UNIVERSIDAD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Verificación de email (false = desactivado en desarrollo)
app.email.verification.enabled=false

resend.api-key=${RESEND_API_KEY}
resend.from-email=onboarding@resend.dev

app.jwt.secret=${JWT_SECRET:mypelink-secret-key-cajamarca-2026-upn-capstone-muy-larga}
app.jwt.expiration=86400000

spring.flyway.enabled=false
spring.jpa.open-in-view=false
server.port=8080

logging.level.org.springframework.security=DEBUG
logging.level.com.mypelink=DEBUG